version: '3.8'

services:
  account:
    image: 'teamdef/agora-back-account:0.1.0'
    restart: 'unless-stopped'
    ports:
      - '8080:8080'

  main:
    image: 'teamdef/agora-back-main:0.1.1'
    restart: 'unless-stopped'
    ports:
      - '8090:8090'
